apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: containers-for-anxious-people
spec:
  rules:
  - host: containers-for-anxious-people.integr8.app
    http:
      paths:
      - path: /
        backend:
          serviceName: containers-for-anxious-people
          servicePort: 80
  tls:
    - hosts:
      - containers-for-anxious-people.integr8.app
      secretName: containers-for-anxious-people-integr8-app-tls