sudo: true
language: c
compiler: gcc

services:
  - docker

jobs:
  include:
    - stage: "Publish docs"
      script:
        - mkdir -p output
        - cp -r $TRAVIS_BUILD_DIR/resources/image output/
        - docker run --rm -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor asciidoctor -o index.html -r asciidoctor-diagram  -D output -a plantuml-config=resources/plantuml/plantuml.cfg main.adoc
        - docker run --rm -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -o doc.pdf -r asciidoctor-diagram  -D output -a plantuml-config=resources/plantuml/plantuml.cfg main.adoc
        - docker run --rm -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0 -o presentation.html -r asciidoctor-diagram  -D output -a plantuml-config=resources/plantuml/plantuml.cfg main.adoc
        - sudo rm -rf $TRAVIS_BUILD_DIR/output/.asciidoctor
      deploy:
        provider: pages
        target-branch: gh-pages
        skip_cleanup: true
        local_dir: output/
        github_token: $GH_TOKEN
        on:
          branch: development
