language: python
python:
  - "3.7.1"
services:
  - docker

cache:
  directories:
    - $TRAVIS_BUILD_DIR/output/

before_script:
  - sudo apt-get install -y ghostscript

jobs:
  include:
    - stage: Build HTML and PDF
      script:
        - make build_html
        - make build_pdf
        - make build_presentation
        - make optimize_pdf

    - stage: Build Docker Image and Push to Docker Hub
      if: tag is present
      script:
        - make build_docker_image 
        - make push_docker_image